# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTlmNTJjMzUyODAyZjhjYjk1NGRhODM1MDFlYmIwMTA2MDhkZGRlMDlmNjY5ZmU0YmNkM2FiZDUyOTE0ODlhMmQxNzY5ZGQxZjYxYjY2YTM4YmYzMjNlNWI5NDk5Y2ZlODNkMjY2MTU0ODg2NmZmYTVmODE5NDhiMDkyOWM0NjQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
